//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.1
// Date Of Creation: 2/21/2013 12:56:44 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>
#import "SampleService_Enums.h"
#import "NSData+Base64.h"
#import "Request.h"
#import "Response.h"


@interface SampleService : NSObject
{
}
@property SoapProtocolVersion soapVersion;
@property BOOL allowAutoRedirect;
@property BOOL enableDecompression;
@property (nonatomic, copy) NSString *userAgent;
@property BOOL unsafeAuthenticatedConnectionSharing;
@property BOOL useDefaultCredentials;
@property (nonatomic, copy) NSString *connectionGroupName;
@property BOOL preAuthenticate;
@property (nonatomic, copy) NSString *url;
@property int timeout;
@property (nonatomic, assign) void(*targetAction)(id target,id sender,NSString* theXml);
@property (nonatomic,assign) id actionDelegate;
@property (nonatomic, retain) NSURLConnection *wsConnection;
@property (nonatomic, retain) NSMutableData *webData;
@property (nonatomic, retain) NSError *error;
@property (nonatomic, retain) NSMutableDictionary *requestHeaders;
@property (nonatomic, copy)   NSString *eventName;

///Origin Return Type:NSString
-(void)HelloWorld;
///Origin Return Type:NSData
-(void)GetByteArray;
///Origin Return Type:NSData
-(void)GetBackByteArray:(NSData*)data ;
///Origin Return Type:Response
-(void)ServiceSample:(Request *)req ;
///Origin Return Type:NSMutableArray
-(void)getListStrings;
///Origin Return Type:NSMutableArray
-(void)GetListOfCustomObject;
///Origin Return Type:NSString
-(void)GetString;
///Origin Return Type:int
-(void)GetInt32;
///Origin Return Type:short
-(void)GetInt16;
///Origin Return Type:long
-(void)GetInt64;
///Origin Return Type:double
-(void)GetDouble;
///Origin Return Type:long
-(void)GetLong;
///Origin Return Type:WSPerson
-(void)GetPerson;
///Origin Return Type:TestEnum
-(void)GetEnum;
///Origin Return Type:
-(void)GetVoid;
///Origin Return Type:NSString
-(void)sendEnum:(TestEnum)enum1 ;
///Origin Return Type:TestEnum
-(void)getEnum:(TestEnum)enum2 ;
-(id) initWithTarget:(id)target  AndAction:(void(*)(id target,id sender ,NSString* theXml))action;
-(void) addTarget:(id)target AndAction:(void(*)(id target,id sender ,NSString* theXml))action;
@end
