//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.1
// Date Of Creation: 10/3/2018 10:15:47 AM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>
#import "AOPT_Enums.h"
#import "APPSXXDC_AOPT_PKG_WSX1843128X6X5.h"
#import "DocUploadDTO.h"
#import "Base64Binary.h"


@interface AOPT : NSObject
{
}
@property SoapProtocolVersion soapVersion;
@property BOOL allowAutoRedirect;
@property BOOL enableDecompression;
@property (nonatomic, copy) NSString *userAgent;
@property BOOL unsafeAuthenticatedConnectionSharing;
@property BOOL useDefaultCredentials;
@property (nonatomic, copy) NSString *connectionGroupName;
@property BOOL preAuthenticate;
@property (nonatomic, copy) NSString *url;
@property int timeout;
@property (nonatomic, assign) void(*targetAction)(id target,id sender,NSString* xml);
@property (nonatomic,assign) id actionDelegate;
@property (nonatomic, strong) NSURLConnection *wsConnection;
@property (nonatomic, strong) NSMutableData *webData;
@property (nonatomic, strong) NSError *error;
@property (nonatomic, strong) NSMutableDictionary *requestHeaders;
@property (nonatomic, copy)   NSString *eventName;

///Origin Return Type:NSString
-(void)EarlyHandoverPaymentPlanCreation:(NSString *)P_REGISTRATION_ID :(NSString *)P_SR_NUMBER :(NSString *)P_SR_TYPE :(NSString *)REGISTRATION_ID :(NSString *)INSTALLMENT :(NSString *)DESCRIPTION :(NSString *)PAYMENT_DATE :(NSString *)EXPECTED_DATE :(NSString *)MILESTONE_EVENT :(NSString *)PERCENT_VALUE :(NSString *)TRANSFER_AR_INTER_FLAG :(NSString *)PAYMENT_AMOUNT ;
///Origin Return Type:NSString
-(void)PaymentPlanReversalMultiple:(NSString *)P_REGISTRATION_ID :(NSString *)P_SR_NUMBER ;
///Origin Return Type:NSString
-(void)PaymentPlanCreation:(NSString *)P_REGISTRATION_ID :(NSString *)P_SR_NUMBER :(NSString *)P_SR_TYPE :(NSMutableArray *)regTerms ;
///Origin Return Type:NSString
-(void)PaymentPlanReversal:(NSString *)P_REGISTRATION_ID :(NSString *)P_SR_NUMBER ;
///Origin Return Type:NSString
-(void)DocumentAttachmentMultiple:(NSString *)P_REQUEST_NUMBER :(NSString *)P_REQUEST_NAME :(NSString *)P_SOURCE_SYSTEM :(NSMutableArray *)regTerms ;
///Origin Return Type:NSString
-(void)DocumentAttachment:(NSString *)P_REQUEST_NUMBER :(NSString *)P_REQUEST_NAME :(NSString *)P_SOURCE_SYSTEM :(NSString *)SourceId :(NSString *)RegistrationId :(NSString *)EntityName :(NSString *)Category :(NSString *)FileId :(NSString *)FileName :(NSString *)FileDescription :(NSString *)SourceFileName :(Base64Binary *)b ;
///Origin Return Type:NSString
-(void)getMilestonePaymentDetails:(NSString *)REGISTRATION_ID ;
///Origin Return Type:NSString
-(void)RegistrationDetails:(NSString *)P_REGISTRATION_ID :(NSString *)P_SR_NUMBER ;
///Origin Return Type:NSString
-(void)PaymentPlanHistory:(NSString *)P_REGISTRATION_ID :(NSString *)P_SR_NUMBER ;
///Origin Return Type:NSString
-(void)PaymentPlanReversalCurrent:(NSString *)P_REGISTRATION_ID :(NSString *)P_SR_NUMBER ;
///Origin Return Type:NSString
-(void)getMasterMilestone:(NSString *)REGISTRATION_ID ;
-(id) initWithTarget:(id)target  AndAction:(void(*)(id target,id sender ,NSString* xml))action;
-(void) addTarget:(id)target AndAction:(void(*)(id target,id sender ,NSString* xml))action;
@end
