//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.1
// Date Of Creation: 10/3/2018 10:15:47 AM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>


@interface APPSXXDC_AOPT_PKG_WSX1843128X6X5 : NSObject
{
}
@property (nonatomic, copy) NSString *dESCRIPTION;
@property (nonatomic, copy) NSString *eXPECTED_DATE;
@property (nonatomic, copy) NSString *iNSTALLMENT;
@property (nonatomic, copy) NSString *lINE_ID;
@property (nonatomic, copy) NSString *mILESTONE_EVENT;
@property (nonatomic, copy) NSString *pAYMENT_AMOUNT;
@property (nonatomic, copy) NSString *pAYMENT_DATE;
@property (nonatomic, copy) NSString *pDC_AMOUNT;
@property (nonatomic, copy) NSString *pDC_DATE;
@property (nonatomic, copy) NSString *pDC_NUMBER;
@property (nonatomic, copy) NSString *pERCENT_VALUE;
@property (nonatomic, copy) NSString *rEGISTRATION_ID;
@property (nonatomic, copy) NSString *sTATUS;
@property (nonatomic, copy) NSString *tERM_ID;
@property (nonatomic, copy) NSString *tRANSFER_AR_INTER_FLAG;

-(NSString*)toString:(BOOL)addNameWrap;
-(id)initWithArray:(NSArray*)array;
-(void)encodeWithCoder:(NSCoder *)encoder;
-(id)copyWithZone:(NSZone *)zone;
-(id)initWithCoder:(NSCoder *)decoder;
@end
