//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.1
// Date Of Creation: 10/3/2018 10:15:47 AM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import "APPSXXDC_AOPT_PKG_WSX1843128X6X5.h" 


@implementation APPSXXDC_AOPT_PKG_WSX1843128X6X5

-(id)initWithArray:(NSArray*)array {
    self = [super init];
    if (self) {
        @try {
            for (int i0 = 0; i0 < [array count]; i0++)
            {
                if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"DESCRIPTION"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setDESCRIPTION:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"EXPECTED_DATE"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setEXPECTED_DATE:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"INSTALLMENT"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setINSTALLMENT:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"LINE_ID"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setLINE_ID:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"MILESTONE_EVENT"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setMILESTONE_EVENT:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"PAYMENT_AMOUNT"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPAYMENT_AMOUNT:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"PAYMENT_DATE"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPAYMENT_DATE:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"PDC_AMOUNT"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPDC_AMOUNT:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"PDC_DATE"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPDC_DATE:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"PDC_NUMBER"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPDC_NUMBER:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"PERCENT_VALUE"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPERCENT_VALUE:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"REGISTRATION_ID"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setREGISTRATION_ID:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"STATUS"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setSTATUS:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"TERM_ID"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setTERM_ID:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"TRANSFER_AR_INTER_FLAG"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setTRANSFER_AR_INTER_FLAG:nodeContentValue];
                }
            }
        }
        @catch(NSException *ex){
        }
    }
    return self;
}
-(NSString*)toString:(BOOL)addNameWrap {
    NSMutableString *nsString = [NSMutableString string];
    if (addNameWrap == YES)
        [nsString appendString:@"<APPSXXDC_AOPT_PKG_WSX1843128X6X5>" ];
    if (self.dESCRIPTION != nil) {
        [nsString appendFormat:@"<DESCRIPTION>%@</DESCRIPTION>" , [self dESCRIPTION]];
    }
    if (self.eXPECTED_DATE != nil) {
        [nsString appendFormat:@"<EXPECTED_DATE>%@</EXPECTED_DATE>" , [self eXPECTED_DATE]];
    }
    if (self.iNSTALLMENT != nil) {
        [nsString appendFormat:@"<INSTALLMENT>%@</INSTALLMENT>" , [self iNSTALLMENT]];
    }
    if (self.lINE_ID != nil) {
        [nsString appendFormat:@"<LINE_ID>%@</LINE_ID>" , [self lINE_ID]];
    }
    if (self.mILESTONE_EVENT != nil) {
        [nsString appendFormat:@"<MILESTONE_EVENT>%@</MILESTONE_EVENT>" , [self mILESTONE_EVENT]];
    }
    if (self.pAYMENT_AMOUNT != nil) {
        [nsString appendFormat:@"<PAYMENT_AMOUNT>%@</PAYMENT_AMOUNT>" , [self pAYMENT_AMOUNT]];
    }
    if (self.pAYMENT_DATE != nil) {
        [nsString appendFormat:@"<PAYMENT_DATE>%@</PAYMENT_DATE>" , [self pAYMENT_DATE]];
    }
    if (self.pDC_AMOUNT != nil) {
        [nsString appendFormat:@"<PDC_AMOUNT>%@</PDC_AMOUNT>" , [self pDC_AMOUNT]];
    }
    if (self.pDC_DATE != nil) {
        [nsString appendFormat:@"<PDC_DATE>%@</PDC_DATE>" , [self pDC_DATE]];
    }
    if (self.pDC_NUMBER != nil) {
        [nsString appendFormat:@"<PDC_NUMBER>%@</PDC_NUMBER>" , [self pDC_NUMBER]];
    }
    if (self.pERCENT_VALUE != nil) {
        [nsString appendFormat:@"<PERCENT_VALUE>%@</PERCENT_VALUE>" , [self pERCENT_VALUE]];
    }
    if (self.rEGISTRATION_ID != nil) {
        [nsString appendFormat:@"<REGISTRATION_ID>%@</REGISTRATION_ID>" , [self rEGISTRATION_ID]];
    }
    if (self.sTATUS != nil) {
        [nsString appendFormat:@"<STATUS>%@</STATUS>" , [self sTATUS]];
    }
    if (self.tERM_ID != nil) {
        [nsString appendFormat:@"<TERM_ID>%@</TERM_ID>" , [self tERM_ID]];
    }
    if (self.tRANSFER_AR_INTER_FLAG != nil) {
        [nsString appendFormat:@"<TRANSFER_AR_INTER_FLAG>%@</TRANSFER_AR_INTER_FLAG>" , [self tRANSFER_AR_INTER_FLAG]];
    }
    if (addNameWrap == YES)
        [nsString appendString:@"</APPSXXDC_AOPT_PKG_WSX1843128X6X5>" ];
    return nsString;
}
#pragma mark - NSCoding
-(id)initWithCoder:(NSCoder *)decoder{
    self = [super init];
    if (self){
        self.dESCRIPTION = [decoder decodeObjectForKey:@"dESCRIPTION"];
        self.eXPECTED_DATE = [decoder decodeObjectForKey:@"eXPECTED_DATE"];
        self.iNSTALLMENT = [decoder decodeObjectForKey:@"iNSTALLMENT"];
        self.lINE_ID = [decoder decodeObjectForKey:@"lINE_ID"];
        self.mILESTONE_EVENT = [decoder decodeObjectForKey:@"mILESTONE_EVENT"];
        self.pAYMENT_AMOUNT = [decoder decodeObjectForKey:@"pAYMENT_AMOUNT"];
        self.pAYMENT_DATE = [decoder decodeObjectForKey:@"pAYMENT_DATE"];
        self.pDC_AMOUNT = [decoder decodeObjectForKey:@"pDC_AMOUNT"];
        self.pDC_DATE = [decoder decodeObjectForKey:@"pDC_DATE"];
        self.pDC_NUMBER = [decoder decodeObjectForKey:@"pDC_NUMBER"];
        self.pERCENT_VALUE = [decoder decodeObjectForKey:@"pERCENT_VALUE"];
        self.rEGISTRATION_ID = [decoder decodeObjectForKey:@"rEGISTRATION_ID"];
        self.sTATUS = [decoder decodeObjectForKey:@"sTATUS"];
        self.tERM_ID = [decoder decodeObjectForKey:@"tERM_ID"];
        self.tRANSFER_AR_INTER_FLAG = [decoder decodeObjectForKey:@"tRANSFER_AR_INTER_FLAG"];
    }
    return self;
}
-(void)encodeWithCoder:(NSCoder *)encoder{
    [encoder encodeObject:self.dESCRIPTION forKey:@"dESCRIPTION"];
    [encoder encodeObject:self.eXPECTED_DATE forKey:@"eXPECTED_DATE"];
    [encoder encodeObject:self.iNSTALLMENT forKey:@"iNSTALLMENT"];
    [encoder encodeObject:self.lINE_ID forKey:@"lINE_ID"];
    [encoder encodeObject:self.mILESTONE_EVENT forKey:@"mILESTONE_EVENT"];
    [encoder encodeObject:self.pAYMENT_AMOUNT forKey:@"pAYMENT_AMOUNT"];
    [encoder encodeObject:self.pAYMENT_DATE forKey:@"pAYMENT_DATE"];
    [encoder encodeObject:self.pDC_AMOUNT forKey:@"pDC_AMOUNT"];
    [encoder encodeObject:self.pDC_DATE forKey:@"pDC_DATE"];
    [encoder encodeObject:self.pDC_NUMBER forKey:@"pDC_NUMBER"];
    [encoder encodeObject:self.pERCENT_VALUE forKey:@"pERCENT_VALUE"];
    [encoder encodeObject:self.rEGISTRATION_ID forKey:@"rEGISTRATION_ID"];
    [encoder encodeObject:self.sTATUS forKey:@"sTATUS"];
    [encoder encodeObject:self.tERM_ID forKey:@"tERM_ID"];
    [encoder encodeObject:self.tRANSFER_AR_INTER_FLAG forKey:@"tRANSFER_AR_INTER_FLAG"];
}
-(id)copyWithZone:(NSZone *)zone {
    APPSXXDC_AOPT_PKG_WSX1843128X6X5 *finalCopy = [[[self class] allocWithZone: zone] init];
    
    NSString *copy1 = [self.dESCRIPTION copy];
    finalCopy.dESCRIPTION = copy1;
    
    NSString *copy2 = [self.eXPECTED_DATE copy];
    finalCopy.eXPECTED_DATE = copy2;
    
    NSString *copy3 = [self.iNSTALLMENT copy];
    finalCopy.iNSTALLMENT = copy3;
    
    NSString *copy4 = [self.lINE_ID copy];
    finalCopy.lINE_ID = copy4;
    
    NSString *copy5 = [self.mILESTONE_EVENT copy];
    finalCopy.mILESTONE_EVENT = copy5;
    
    NSString *copy6 = [self.pAYMENT_AMOUNT copy];
    finalCopy.pAYMENT_AMOUNT = copy6;
    
    NSString *copy7 = [self.pAYMENT_DATE copy];
    finalCopy.pAYMENT_DATE = copy7;
    
    NSString *copy8 = [self.pDC_AMOUNT copy];
    finalCopy.pDC_AMOUNT = copy8;
    
    NSString *copy9 = [self.pDC_DATE copy];
    finalCopy.pDC_DATE = copy9;
    
    NSString *copy10 = [self.pDC_NUMBER copy];
    finalCopy.pDC_NUMBER = copy10;
    
    NSString *copy11 = [self.pERCENT_VALUE copy];
    finalCopy.pERCENT_VALUE = copy11;
    
    NSString *copy12 = [self.rEGISTRATION_ID copy];
    finalCopy.rEGISTRATION_ID = copy12;
    
    NSString *copy13 = [self.sTATUS copy];
    finalCopy.sTATUS = copy13;
    
    NSString *copy14 = [self.tERM_ID copy];
    finalCopy.tERM_ID = copy14;
    
    NSString *copy15 = [self.tRANSFER_AR_INTER_FLAG copy];
    finalCopy.tRANSFER_AR_INTER_FLAG = copy15;
    
    return finalCopy;
}

@end
