//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.1
// Date Of Creation: 10/3/2018 10:15:47 AM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>
#import "Base64Binary.h"


@interface DocUploadDTO : NSObject
{
}
@property (nonatomic, copy) NSString *category;
@property (nonatomic, copy) NSString *entityName;
@property (nonatomic, strong) Base64Binary *fileBinary;
@property (nonatomic, copy) NSString *fileDescription;
@property (nonatomic, copy) NSString *fileId;
@property (nonatomic, copy) NSString *fileName;
@property (nonatomic, copy) NSString *registrationId;
@property (nonatomic, copy) NSString *sourceFileName;
@property (nonatomic, copy) NSString *sourceId;

-(NSString*)toString:(BOOL)addNameWrap;
-(id)initWithArray:(NSArray*)array;
-(void)encodeWithCoder:(NSCoder *)encoder;
-(id)copyWithZone:(NSZone *)zone;
-(id)initWithCoder:(NSCoder *)decoder;
@end
