//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.1
// Date Of Creation: 2/21/2013 12:56:44 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import "Request.h" 


@implementation Request

-(id)initWithArray:(NSArray*)array {
    self = [super init];
    if (self) {
        @try {
            for (int i0 = 0; i0 < [array count]; i0++)
            {
                if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"companyId"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCompanyId:nodeContentValue];
                    [nodeContentValue release];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"userName"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setUserName:nodeContentValue];
                    [nodeContentValue release];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"Password"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPassword:nodeContentValue];
                    [nodeContentValue release];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"byteArray"]==NSOrderedSame)){
                    NSString* stringData = [[array  objectAtIndex:i0] objectForKey:@"nodeContentValue"];
                    NSData* nodeContentValue = [NSData dataFromBase64String:stringData];
                    [self setByteArray:nodeContentValue];
                    [nodeContentValue release];
                }
            }
        }
        @catch(NSException *ex){
        }
    }
    return self;
}
-(NSString*)toString:(BOOL)addNameWrap {
    NSMutableString *nsString = [NSMutableString string];
    if (addNameWrap == YES)
        [nsString appendString:@"<Request>" ];
    if (self.companyId != nil) {
        [nsString appendFormat:@"<companyId>%@</companyId>" , [self companyId]];
    }
    if (self.userName != nil) {
        [nsString appendFormat:@"<userName>%@</userName>" , [self userName]];
    }
    if (self.password != nil) {
        [nsString appendFormat:@"<Password>%@</Password>" , [self password]];
    }
    if (self.byteArray != nil) {
        [nsString appendFormat:@"<byteArray>%@<byteArray>",[self.byteArray base64EncodedString]];
    }
    if (addNameWrap == YES)
        [nsString appendString:@"</Request>" ];
    return nsString;
}

-(void)dealloc{
    [_companyId release];
    [_userName release];
    [_password release];
    [_byteArray release];
    [super dealloc];
}
@end
