//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.1
// Date Of Creation: 2/21/2013 12:56:44 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import "WSPerson.h" 


@implementation WSPerson

-(id)initWithArray:(NSArray*)array {
    self = [super init];
    if (self) {
        @try {
            for (int i0 = 0; i0 < [array count]; i0++)
            {
                if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"FirstName"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setFirstName:nodeContentValue];
                    [nodeContentValue release];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"LastName"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setLastName:nodeContentValue];
                    [nodeContentValue release];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeChildArray"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"Address"]==NSOrderedSame)){
                    NSArray* arrayXml = [[array  objectAtIndex:i0] objectForKey:@"nodeChildArray"];
                    WSAddress* nodeContentValue = [[WSAddress alloc] initWithArray:arrayXml];
                    [self setAddress:nodeContentValue];
                    [nodeContentValue release];
                }
            }
        }
        @catch(NSException *ex){
        }
    }
    return self;
}
-(NSString*)toString:(BOOL)addNameWrap {
    NSMutableString *nsString = [NSMutableString string];
    if (addNameWrap == YES)
        [nsString appendString:@"<WSPerson>" ];
    if (self.firstName != nil) {
        [nsString appendFormat:@"<FirstName>%@</FirstName>" , [self firstName]];
    }
    if (self.lastName != nil) {
        [nsString appendFormat:@"<LastName>%@</LastName>" , [self lastName]];
    }
    if (self.address != nil) {
        [nsString appendFormat:@"<Address>%@</Address>" , [self.address toString:NO]];
    }
    if (addNameWrap == YES)
        [nsString appendString:@"</WSPerson>" ];
    return nsString;
}

-(void)dealloc{
    [_firstName release];
    [_lastName release];
    [_address release];
    [super dealloc];
}
@end
